Entrega primeiro exercicio
SerenityInAllThings/exercicios_guanabara_js pull request #1
Opened 2022-05-17 00:31 UTC by LucasRatzz

teste primeiro Pull Request

2022-05-17 00:36 UTC, SerenityInAllThings requested changes

2022-05-17 00:36 UTC, SerenityInAllThings commented on lista/01/lucas.js
> +function saudar() {
Use arrow functions

2022-05-17 00:48 UTC, LucasRatzz commented
@_@

2022-05-18 04:54 UTC, SerenityInAllThings requested changes
Excelente! Todos exercícios praticamente corretos, apenas algumas correções simples.

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/01/lucas.js
> +  console.log (`Olá, ${nome}! `)
Espaço desnecessário no final da string. Não é necessário correção, o exercício está correto.

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/02/lucas.js
> +const nome = () => {
Em geral, tente utilizar algum verbo no nome da função. [Tem um material aqui](https://pt.stackoverflow.com/questions/106061/quais-as-melhores-pr%C3%A1ticas-para-dar-nome-%C3%A0s-fun%C3%A7%C3%B5es) para te orientar de forma mais geral também.
Na linha 9 vc passou vários parâmetros na função console.log para concatenar os valores, muito bem! Essa é uma forma 100% válida, mas vale a pena tentar manter um padrão já que no exercício 1 você utilizou [string templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) para concatenar.
Somento a correção do nome da função é necessária.

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/03/lucas.js
> +mostrarSalario()
Excelente!

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/04/lucas.js
> +mostrarSoma()
Excelente!

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/05/lucas.js
> +  console.log ("A média entre", notaUm, "e", notaDois, "é igual a", (notaUm+notaDois) / 2)
No momento não suporta notas quebradas como 4.5 ou 7.5 🌵

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/05/lucas.js
> +monstrarMédia()
Eu não costumo usar acentuação em programas, acho que em JS é tranquilo, mas em algumas linguagens de programação/ambiente pode dar problemas.
No final das contas é preferência pessoal.

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/06/lucas.js
> +monstrarNumMenorMaior()
Excelente!

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/07/lucas.js
> +mostrarNumRealDobroTerc();
No momento a função não suporta números reais, apenas inteiros :C
Sobre os comentários abaixo, eu ou os removeria ou tentaria deixar eles mais detalhados.

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/08/lucas.js
> +distância()
Excelente!

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/09/lucas.js
> +quantiaDinheiro()
Mesmo comentário sobre os verbos nos nomes de função.
A função só suporta números inteiros no momento.

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/10/lucas.js
> +dimensões()
Corrigir o nome da função.

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/11/lucas.js
> +mostrarValorDelta()
Excelente!

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/12/lucas.js
> +lerPreços();
Atualmente só suporta números inteiros

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/13/lucas.js
> +novoSalario();
Aqui temos duas formas de resolver, bem legal.
Tenta melhorar o nome da segunda função, por favor.
Além disso, as funções não suportam números reais no momento.

2022-05-18 04:54 UTC, SerenityInAllThings commented on lista/15/lucas.js
> +lerDiasTrabalhados();
Excelente!
Cuidado para não se confundir com os nomes de variáveis. Nesse caso, por exemplo, a variável `diasTrabalhados` no início representa a ideia de dias trabalhados e depois representa o salário.

2022-05-26 00:14 UTC, vincenzo-bbosco commented on lista/11/lucas.js
> +mostrarValorDelta()
Muito bom

2022-05-26 04:07 UTC, mnkdoit commented on lista/08/lucas.js
> +    console.log (valorNum*1000+"Mm")
Excelente!
Você pode deixar melhor ajustando o uso do espaço, ex:
Entre o 'parenteses' de função não é necessário - console.log('texto') [Sem espaço]
Dando espaço entre operadores - console.log(valorNum * 0.100000 + "Dam")
9/10, eu comia

2022-05-26 04:11 UTC, mnkdoit commented on lista/16/lucas.js
> +    cigarro = (cigarro * 365 * ano * 10) / 60 / 24
Trocar a variável cigarro por uma que remeta ao tempo seria legal. Não tem diferença prática, mas melhora leitura

2022-05-26 04:17 UTC, mnkdoit commented on lista/18/lucas.js
> +        console.log ("Meus parabéns, você já pode tirar o seu titulo de eleitor")
E votar no bolsonaro

2022-06-01 23:58 UTC, SerenityInAllThings commented on lista/07/lucas.js
> +mostrarNumRealDobroTerc();
Ainda não suporta números reais 🌵

2022-06-01 23:58 UTC, SerenityInAllThings commented on lista/09/lucas.js
> +quantiaDinheiro()
Nome ainda inadequado.

2022-06-01 23:59 UTC, SerenityInAllThings commented on lista/13/lucas.js
> +novoSalario();
Nomes ainda ruins

2022-06-02 00:16 UTC, SerenityInAllThings approved these changes

2022-06-02 00:16 UTC, merged