Primeira leva de exercícios
SerenityInAllThings/exercicios_guanabara_js pull request #2
Opened 2022-05-26 00:13 UTC by vincenzo-bbosco

Estou subindo os meus bolsonarinhos

2022-05-26 03:41 UTC, mnkdoit commented on lista/03/Vincenzo-03.js
> +    const replaceString = prompt("Salario do Funcionario:").replace(",",".")
Altámente quebrável

2022-05-26 03:43 UTC, mnkdoit commented on lista/04/Vincenzo-04.js
> +    console.log("A soma entre 8 e 5 é igual a",somaNum1_2.toString())
Todo objeto em saída de console já é convertido pra string por padrão

2022-05-26 03:52 UTC, mnkdoit commented on lista/25/Vincenzo-25-30.js
> +    if (isTriangle ) {
Porque esse if não tem corpo ?

2022-05-26 03:52 UTC, mnkdoit commented on lista/25/Vincenzo-25-30.js
> +        console.log('bolsonaro')
Presidente

2022-05-26 03:53 UTC, mnkdoit requested changes
Leia os comentários

2022-05-30 22:20 UTC, SerenityInAllThings requested changes

2022-05-30 22:20 UTC, SerenityInAllThings commented on lista/01/Vincenzo-01.js
> +// 1) Escreva um programa que mostre na tela a mensagem "Olá, Mundo!"
O exercício só pede para imprimir a mensagem na tela, por isso, não é necessário usar o prompt-sync.
Para imprimir coisas em js, pode-se usar o [console.log](https://developer.mozilla.org/en-US/docs/Web/API/console/log)

2022-05-30 22:20 UTC, SerenityInAllThings commented on lista/01/Vincenzo-01.js
> +  const MensagemTela = prompt("Olá Mundo");
Como basta imprimir na tela, tbm não é necessário declarar variáveis.

2022-05-30 22:20 UTC, SerenityInAllThings commented on lista/02/Vincenzo-02.js
> +    const Nome = prompt("Qual é o seu nome?")
em geral em JS se utiliza [camelCase ](https://coodesh.com/blog/dicionario/o-que-e-camelcase/)para nome de variáveis.
[Outros guidelines e naming conventions de JS](https://www.w3schools.com/js/js_conventions.asp)

2022-05-30 22:20 UTC, SerenityInAllThings commented on lista/02/Vincenzo-02.js
> +  const Nome = prompt("Qual é o seu nome?");
Em JS costuma-se utilizar [camelCase ](https://coodesh.com/blog/dicionario/o-que-e-camelcase/)para nomes de variáveis.
Segue uma referência de [outros naming conventions em JS](https://www.w3schools.com/js/js_conventions.asp)

2022-05-30 22:20 UTC, SerenityInAllThings commented on lista/03/Vincenzo-03.js
> +const prompt = require("prompt-sync")({});
Excelente

2022-05-30 22:20 UTC, SerenityInAllThings commented on lista/04/Vincenzo-04.js
> +    console.log("A soma entre 8 e 5 é igual a",somaNum1_2.toString())
Por isso, o .toString() é desnecessário aqui

2022-05-30 22:20 UTC, SerenityInAllThings commented on lista/04/Vincenzo-04.js
> +  const somaNum1_2 = numero1 + numero2;
Acho que dado o contexto dessa função, é razoável simplificar o nome da variável para apenas `nome`

2022-05-30 22:20 UTC, SerenityInAllThings commented on lista/01/Vincenzo-01.js
> +const Mensagem = () => {
Tente ter pelo menos um verbo no infinitivo no nome da função. Além disso, tente usar [camelCase](https://coodesh.com/blog/dicionario/o-que-e-camelcase/)

2022-05-30 22:20 UTC, SerenityInAllThings commented on lista/05/Vincenzo-05.js
> +const prompt = require('prompt-sync')({})
Excelente

2022-05-30 22:20 UTC, SerenityInAllThings commented on lista/04/Vincenzo-04.js
> +  console.log("A soma entre 8 e 5 é igual a", somaNum1_2.toString());
Tente substituir o `8` e o `5` pelos valores inputados pelo usuário.

2022-06-06 22:46 UTC, vincenzo-bbosco commented on lista/25/Vincenzo-25-30.js
> +    if (isTriangle ) {
por algum motivo eu deixei o corpo do if comentado kkkkkkkkkk

2022-06-13 22:16 UTC, SerenityInAllThings approved these changes

2022-07-05 00:19 UTC, SerenityInAllThings commented
boa
rato

2022-07-05 00:20 UTC, merged